cargo-features = ["edition2024"]

[package]
name = "amm_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1" }
syn = { version = "2", features = ["full"] }
